name: Update Factbook Data

on:
  schedule:
    - cron: '0 0 * * MON'  # This schedules the action to run at 00:00 every Monday
  workflow_dispatch: # This allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout target repo
      uses: actions/checkout@v2
      with:
        repository: KuzonFyre/World-FactBook-Vis
        token: ${{ secrets.PAT_TOKEN }}
        path: World-FactBook-Vis
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Specify your Python version
    - name: setup web scraper
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        wget https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/bin/chromedriver
        sudo chown root:root /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver
    - name: Install Dependencies
      run: |
        pip install pandas
        pip install pycountry
        pip install webdriver_manager
        pip install selenium
        pip install beautifulsoup4
    - name: Process JSON Files
      run: |
        cd World-FactBook-Vis/.github/
        ls -lah
        echo "Now in $(pwd)"
        python cia_factbook_scaper.py
        
    - name: Push changes
      working-directory: World-FactBook-Vis
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add -A
        git commit -m "Weekly factbook data update" || echo "No changes to commit"
        git push
    
