name: Update Factbook Data

on:
  schedule:
    - cron: '0 0 * * MON'  # This schedules the action to run at 00:00 every Monday
  workflow_dispatch: # This allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repo
      uses: actions/checkout@v2
      with:
        repository: factbook/factbook.json
        path: factbook

    - name: Checkout target repo
      uses: actions/checkout@v2
      with:
        repository: KuzonFyre/World-FactBook-Vis
        token: ${{ secrets.PAT_TOKEN }} # This uses your PAT for authentication
        path: World-FactBook-Vis

    - name: Copy factbook data
      run: |
        cp -r factbook/north-america/. World-FactBook-Vis/data/north-america

    - name: Push changes
      working-directory: World-FactBook-Vis
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add -A
        git commit -m "Weekly factbook data update" || echo "No changes to commit"
        git push
