name: Update Factbook Data

on:
  schedule:
    - cron: '0 0 * * MON'  # This schedules the action to run at 00:00 every Monday
  workflow_dispatch: # This allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repo
      uses: actions/checkout@v2
      with:
        repository: factbook/factbook.json
        path: factbook

    - name: Checkout target repo
      uses: actions/checkout@v2
      with:
        repository: KuzonFyre/World-FactBook-Vis
        token: ${{ secrets.PAT_TOKEN }} # This uses your PAT for authentication
        path: World-FactBook-Vis

    - name: Copy factbook data
      run: |
        cp -r factbook/north-america/. World-FactBook-Vis/data/north-america
        cp -r factbook/africa/. World-FactBook-Vis/data/africa
        cp -r factbook/australia-oceania/. World-FactBook-Vis/data/australia-oceania
        cp -r factbook/central-america-n-caribbean/. World-FactBook-Vis/data/central-america-n-caribbean
        cp -r factbook/central-asia/. World-FactBook-Vis/data/central-asia
        cp -r factbook/east-n-southeast-asia/. World-FactBook-Vis/data/east-n-southeast-asia
        cp -r factbook/europe/. World-FactBook-Vis/data/europe
        cp -r factbook/middle-east/. World-FactBook-Vis/data/middle-east
        cp -r factbook/south-america/. World-FactBook-Vis/data/south-america
        cp -r factbook/south-asia/. World-FactBook-Vis/data/south-asia
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify your Python version

    - name: Install Dependencies
      run: |
        pip install pandas
    - name: Process JSON Files
      run: |
        cd World-FactBook-Vis
        ls -lah
        echo "Now in $(pwd)"
        python process_json.py
    - name: Push changes
      working-directory: World-FactBook-Vis
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add -A
        git commit -m "Weekly factbook data update" || echo "No changes to commit"
        git push
    
